### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by frauhottelmann** [crouchingtigerhiddenadam/nano-hat-oled-armbian#1]
Hey there,
thank you for this. Does it work with Python3 though? Python2 is now deprecated I would prefer not installing it any more. The original already doesn't work anymore, because Ubuntu 20.04 is missing some python2 packages :roll_eyes: 

Thanks

**Comment by frauhottelmann** [comment]
Ah, I see that the fork by pumuckly works with python3.

**Comment by crouchingtigerhiddenadam** [comment]
There are forks you can try. I can convert it to Python 3, I am still supporting the code and pull requests are welcome.

**Comment by crouchingtigerhiddenadam** [comment]
There are now Python3 versions:

- install3.sh
- start-oled3.sh

#### install3.sh
The install is slightly different to @pumuckly's version. [Programs are compiled differently in Python 3.](https://www.python.org/dev/peps/pep-3147/#examples).

#### start-oled3.sh
I've also removed tabs which had crept in from somewhere, but are not on my local version.
